### ISSUE TITLE
Why does TVar<T> require T: Any?

### ISSUE THREAD

**Issue by konsumlamm** [Marthog/rust-stm#13]
Why does `TVar<T>` store the `T` value as an `Any` trait object, instead of storing it directly as `T`? It is stored inside an `Arc` anyway, so it shouldn't make a difference? I couldn't find any explanation for this.

**Comment by Marthog** [comment]
A transaction records all changes in a log (see `stm-cor/src/transaction/log_var.rs` and `stm-core/src/transaction.mod`). In this log all variables need to be stored as `Arc<Any+Send+Sync>`, because it can't memorize the concrete type.

When committing, the references are written back into the `VarControlBlock`. 

The log needs a form of type erasure, but the `TVar`s need to cast it back to a concrete type `T`, which is only possible with Any or with unsafe pointer casts. The later would suffice, but I chose to go with a safe implementation, at least for the first iterations.

**Comment by konsumlamm** [comment]
I see, thank you for the explanation!
